appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: PmWE9JAKYU2sOw03HArSlE4Y+u4t7Xj3zpFJcqdnAO+bzXXrfFtmKZvVmVsYLydGWRFVvwOsmabJ+AW3+eDrKdCypMn8HVaHg+GEwq4exnOiaLSxsbFzEms0cTkZveWvugmRan0NlUs9xA4S61VA5R3m4iDHIrUF9rBoBc8emHrsEL/U00gbAxO07sUB7m5FfoykerLiuxYFmcZn/QFwpPZ3bjas+TmYCWtlxMfsioGpjgMQjgIsFGgmEAD7Qq4f5SHMNVpKD3w3HDbYpCuodfWJAAK5QPrKpOQ2TQHP1LhK1DPFXKcxLdnkGEvrgt0vAHJfHXY4jNJzxikjxoOri6KB170JiUakMrDmW/Xr0l2i89+1040m/sa6tIJbJ3EQhjvHL/znA0cSFdFJrk6nedzzOOCYK1ywMskuhO9sKg7YEhg/ymsS/srLvzGpmdUY+TpnOD954sDOivIBPcY50DybMb31bQ/iNStdE0clbXsa+BJm8P/VVV2o5HSx+SMRiwfHuXQ7mXoTdwyPOWltTdPJu8vi5EanY5mMSWRdB8sdyX0TyW0QTxqJh1m05NsYlIblE+KoVhnhMZymUQJRmSuFPABO3GFFHxpgVDT4nMX2vBR+OIxsjRyrqPhcxJvlIf6nLuvkPZ5xwPOeKmhI58+fuRlUSUV3zXHjMi6t75w=
