travis:
  secure:
    BINSTAR_TOKEN: ptjl5SNpGIk+O1Gfw+42KxrJ2oiAh/iuFK+/PrqMAEdKRi6n5hSGzdLuxlp/0LpHd20My9EuTW0EO2Pz3rKZfpH+OgqWLTVn2znT/pIiPRWa6OmCHSB149jiaEYFfbMOY0ENNUo44SAOAihDa/06vI62iL/L4b1fPoH8P9CUM8eq11+XUC9hliTejrfnlGxhslQbNUr+7yo1Xf9u9FsPfzpbK55SgjFjxyOI8yyE/B4VdMVVsiGjW9aBkVWOfJ7lsXNm61HLIeFuFeleOXrcJKZEyHaBUopxLxG/1yZB1ysDHEwo7hlM0E26m35WoAtiSocahtO3SNrkUlOcH4ZW6NT5JnZBs0yRI/D4USXFNV606T1FS3ygU964Zf5i0gB52zBqw2ic2PgluRwVevoN1mGNeU9NQ9wW/XoPW9ejB4buUrq8vd98TTUiXD7bdlfmJudMQAd9SwSN7O+2Cb9pf9WPehLe/2PphG/jjbPsqSpviRs4iSN7IurS8IaGBVsDygU9lLagwPPBBMn0IoCN/EIGN+O93PPtVks5xrZLCNeT4yEgalYvKqd31L72I921z+KT971V0c68QcCyxd0IVUTGlLI+tBb2wDDYyfvJNjB3aRW3ocDrbgklShP63EAk0yybxAKlmu/rnTKy0n18RhQnd4H+fdMrCOwyF4BymM4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
